<?php

/**
 * @OA\Schema(
 *  schema="Hotel",
 *  required={"name", "type", "postal_street", "postal_city", "tel", "	fax",
 *   "url", "check_in", "check_out", "order_id", "menu_order_id",
 *   "video_code", "pms_property_code", "site_url", "latitude",
 *   "longitude", "facebook_url", "googleplus_url"
 *  },
 *  @OA\Property(property="hotel_id", type="integer", example="number"),
 *  @OA\Property(property="country_id", type="integer", example="number"),
 *  @OA\Property(property="region_id", type="integer", example="number"),
 *  @OA\Property(property="rating_id", type="integer", example="number"),
 *  @OA\Property(property="name", type="string", example="string"),
 *  @OA\Property(property="type", type="string", example="string"),
 *  @OA\Property(property="postal_street", type="string", example="string"),
 *  @OA\Property(property="postal_city", type="string", example="string"),
 *  @OA\Property(property="tel", type="string", example="string"),
 *  @OA\Property(property="fax", type="string", example="string"),
 *  @OA\Property(property="url", type="string", example="string"),
 *  @OA\Property(property="check_in", type="date", example="2022-07-22T14:00:00.000000Z"),
 *  @OA\Property(property="check_out", type="date", example="2022-07-22T14:00:00.000000Z"),
 *  @OA\Property(property="status", type="integer", example="number"),
 *  @OA\Property(property="valid_from", type="date", example="2022-07-22T14:00:00.000000Z"),
 *  @OA\Property(property="valid_to", type="date", example="2022-07-22T14:00:00.000000Z"),
 *  @OA\Property(property="thumb_image", type="string", example="string"),
 *  @OA\Property(property="default_image", type="string", example="string"),
 *  @OA\Property(property="order_id", type="integer", example="number"),
 *  @OA\Property(property="menu_order_id", type="integer", example="number"),
 *  @OA\Property(property="hotel_code", type="string", example="string"),
 *  @OA\Property(property="video_code", type="string", example="string"),
 *  @OA\Property(property="pms_property_code", type="integer", example="integer"),
 *  @OA\Property(property="rm_code", type="string", example="string"),
 *  @OA\Property(property="has_villa", type="integer", example="integer"),
 *  @OA\Property(property="has_golf", type="integer", example="integer"),
 *  @OA\Property(property="is_hotel", type="integer", example="integer"),
 *  @OA\Property(property="on_wedding_calendar", type="integer", example="integer"),
 *  @OA\Property(property="site_url", type="string", example="string"),
 *  @OA\Property(property="asterix_id", type="integer", example="integer"),
 *  @OA\Property(property="latitude", type="string", example="string"),
 *  @OA\Property(property="longitude", type="string", example="string"),
 *  @OA\Property(property="facebook_url", type="string", example="string"),
 *  @OA\Property(property="googleplus_url", type="string", example="string"),
 *  @OA\Property(property="reviewpro_script_url", type="string", example="string"),
 *  @OA\Property(property="doc_logo", type="string", example="string"),
 *  @OA\Property(property="status_report_order", type="integer", example="integer"),
 *  @OA\Property(property="on_status_report", type="integer", example="integer"),
 *  @OA\Property(property="wihp_id", type="integer", example="integer"),
 *  @OA\Property(property="ratetiger_code", type="integer", example="integer")
 * )
 */
