<?php

const ERROR_CODE = array(
    'VALIDATOR' => 6,
    'BAD_LOGIN_CREDENTIALS' => 7,
    'INVALID_TOKEN' => 11,
    'EXPIRED_TOKEN' => 12,
    'BLACKLISTED_TOKEN' => 13,
    'TOKEN_NOT_FOUND' => 14,
    'RESOURCE_NOT_FOUND' => 26,
    'NOT_ALLOWED_METHOD' => 31,
    'CR_UNKNOWN_ERROR' => 251,
    'CR_CONNECTION_ERROR' => 252,
    'CR_CONN_HOST_ERROR' => 253,
    'CR_UNKNOWN_HOST' => 254,
    'CR_SERVER_GONE_ERROR' => 255,
    'CR_OUT_OF_MEMORY' => 256,
    'CR_SERVER_LOST' => 257,
    'INTEGRITY_CONSTRAINT_VIOLATION' => 258,
    'GENERIC_ERROR' => 259
);
