name: Release API V2

on:
  push:
    branches: [ "main" ]

# It is important to specify "concurrency" for the workflow,
# to prevent concurrency between different deploys.
# concurrency: production_environment

jobs:
  deploy-staging:
    name: Deploy on Staging
    environment:
      name: staging
    permissions:
      actions: write
      deployments: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOST }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_USER: ${{ secrets.USERNAME }}
          DOT_ENV: ${{ secrets.DOT_ENV_STAGING }}
        run: |
          mkdir -p ~/.ssh/
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/lumen-boiler-template 
          chmod 600 ~/.ssh/lumen-boiler-template 
          cat >>~/.ssh/config <<END
            Host *
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/lumen-boiler-template 
              StrictHostKeyChecking no
          END
      - name: Deploy to Staging
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          dep: deploy stage=staging --tag=${{ env.GITHUB_REF }} -vvv

  deploy-production:
    name: Deploy to Production
    environment:
      name: production
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOST }}
          SSH_HOST: ${{ secrets.HOST }}
          SSH_USER: ${{ secrets.USERNAME }}
          DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
        run: |
          mkdir -p ~/.ssh/
          echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/lumen-boiler-template 
          chmod 600 ~/.ssh/lumen-boiler-template 
          cat >>~/.ssh/config <<END
            Host *
              HostName $SSH_HOST
              User $SSH_USER
              IdentityFile ~/.ssh/lumen-boiler-template 
              StrictHostKeyChecking no
          END
      - name: Deploy to Prod
        uses: deployphp/action@master
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          dep: deploy stage=production --tag=${{ env.GITHUB_REF }} -vvv

