name: Release API V2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-staging:
    name: Deploy Project to STAGING Server
    environment:
      name: staging
    permissions:
      actions: write
      deployments: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
          # To disable host key checking (insecure!):
          ssh-disable-host-key-checking: true
      - name: Deploy to Prod
        env:
          DOT_ENV: ${{ secrets.DOT_ENV_STAGING }}
        run: vendor/bin/dep deploy stage=staging --tag=${{ env.GITHUB_REF }} -vvv

  deploy-production:
    name: Deploy Project to PRODUCTION Server
    environment:
      name: production
    runs-on: ubuntu-latest
    needs: [deploy-staging]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v1
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.2
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      # - name: Setup Deployer
      #   uses: atymic/deployer-php-action@master
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      #     ssh-disable-host-key-checking: true
      # - name: Deploy to Prod
      #   env:
      #     DOT_ENV: ${{ secrets.DOT_ENV_PRODUCTION }}
      #   run: vendor/bin/dep deploy stage=production --tag=${{ env.GITHUB_REF }} -vvv
      - name: Deploy to PRODUCTION Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/lumen-boiler-template
            git pull --ff-only
            # composer i
            # php artisan migrate --force